POST http://localhost:8080/api/v1/customers
Content-Type: application/json

{
      "email":"hoa12345abc@gmail.com",
      "password":"Hoanghoa123@",
      "phone":"0903462434",
      "address":"lệ thủy quảng bình"
}