POST http://localhost:8080/api/v1/customers
Content-Type: application/json

{
      "firstName": "Ngoc Ho",
      "lastName": "Nguyen Nhan",
      "email": "ngocnhan@gmail.com",
      "phone": "0988071443",
      "address": "3121 Spinka Points",
      "password": "Ngocnhan87dn1@23",
      "yard":"SElm Street",
      "district":"Wyoming",
      "province":"Lake Adolfo"
}