POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
    "productName": "Iphone 14",
    "description": "Road bike for paved roads",
    "price": 500,
    "modelYear": "2020",
    "category": "664b405ef273dee2be3b1953",
    "brandId": "664b442031f48b02bb6ba984"
}

###

GET http://localhost:8080/api/v1/products