POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
    "productName": "Iphone 14 Promax",
    "description": "Iphone 14 Promax",
    "price": 1000,
    "modelYear": "2022",
    "category": "{_id:'12345abcde',categoryName:'Iphone'}",
    "brandId": "65f2be7b1d80b8bd5ecsdde",
    "slug":"Iphone14"
}

###

GET http://localhost:8080/api/v1/products